// TASK CREATION (POST)
export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";

// TASK UPDATING (PUT)
export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE";

// GET ALL TASKS (GET)
export const GET_ALL_TASKS_REQUEST = "GET_ALL_TASKS_REQUEST";
export const GET_ALL_TASKS_SUCCESS = "GET_ALL_TASKS_SUCCESS";
export const GET_ALL_TASKS_FAILURE = "GET_ALL_TASKS_FAILURE";

// GET TASK BY STATUS (GET) - *Assuming this is what 'getting the task Status' means*
export const GET_TASKS_BY_STATUS_REQUEST = "GET_TASKS_BY_STATUS_REQUEST";
export const GET_TASKS_BY_STATUS_SUCCESS = "GET_TASKS_BY_STATUS_SUCCESS";
export const GET_TASKS_BY_STATUS_FAILURE = "GET_TASKS_BY_STATUS_FAILURE";

// UPDATE TASK STATUS (PATCH)
export const UPDATE_TASK_STATUS_REQUEST = "UPDATE_TASK_STATUS_REQUEST";
export const UPDATE_TASK_STATUS_SUCCESS = "UPDATE_TASK_STATUS_SUCCESS";
export const UPDATE_TASK_STATUS_FAILURE = "UPDATE_TASK_STATUS_FAILURE";

// DELETE TASK (DEL)
export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";